### ISSUE TITLE
Changing hard coded Port for Sky+HD Receiver

### ISSUE THREAD

**Issue by hstrickling** [ukmoose/node-red-contrib-skyremote#1]
Hello
i tried the Sky Remote Node for Node-Red. The default Port for Sky Box is 49160.
I have a German Sky+HD Box and after an NMAP Scan for Ports on that Box, i found that my Box has an open port on 49153.
At the console of my Node-Red Server i tried a telnet on Port 49160 and got "Connection refused" on Port 49153 i could establish a connection via telnet.
Is it possible to change the default Port from 49160 to 49153 and where?
Or can you make the Port Configuration for the Sky+HD Box editable like the host IP/Name?

Thanks in advanced
Holger

**Comment by ukmoose** [comment]
I wrote it for my UK box and the underlying node doesn't mention other countries using other ports, so I would be interested if this works.  Could you try manually changing the port number in Sky-Remote-config.html (e.g. line 22 https://github.com/ukmoose/node-red-contrib-skyremote/blob/master/SkyRemote-config.html#L22) , restart node-red and see if the node then works? If it does I will add an option in the drop downlist for German Sky Boxes.

Many thanks

Mark

**Comment by hstrickling** [comment]
Hi Mark,

sorry for the late response. Thank you for answering.
I already tried to set my German Box Port in Sky-Remote-config.html and restarted node-red, but somehow the Port doesn’t changed???
I will try it again this evening and give you a short response …

Kind regards
Holger

**Comment by ukmoose** [comment]
Closed due to lack of update
